#!/bin/sh
cd "${0%/*}" || exit                                # Run from this directory
. ${WM_PROJECT_DIR:?}/bin/tools/RunFunctions        # Tutorial run functions
#------------------------------------------------------------------------------

./Allrun.pre
(cd background && decomposePar && mpirun -np 16 $(getApplication) -parallel >log && reconstructPar)

#------------------------------------------------------------------------------
